# infrastructure/helm/prometheus-grafana/values-production.yaml
# Helm values for kube-prometheus-stack in production.

fullnameOverride: "prometheus"

prometheus:
  prometheusSpec:
    retention: 30d # Longer retention for production
    scrapeInterval: "30s"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi # Larger volume for production
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  enabled: true
  # For production, use an Ingress with TLS and authentication
  ingress:
    enabled: true
    ingressClassName: "nginx" # Assuming you have an Ingress controller
    hosts:
      - "grafana.lucid.your-domain.com"
    tls:
      - secretName: grafana-tls-secret
        hosts:
          - grafana.lucid.your-domain.com
  adminPassword: "change-this-secret-password" # Store this in a secret management system
  persistence:
    enabled: true
    type: pvc
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      kserve-dashboard:
        file: dashboards/kserve_dashboard.json
