# .github/workflows/cd-pipeline-staging.yml
# This workflow automates the deployment of the model serving application
# to the staging Kubernetes cluster.

name: Model Serving CD - Staging

on:
  push:
    branches: [ "main" ] # Trigger deployment on merge to main
    paths:
      - 'ml_platform/serving/**' # Only run if serving code changes
      - '.github/workflows/cd-pipeline-staging.yml'

env:
  # Replace with your AWS and container registry details
  AWS_REGION: ca-central-1
  ECR_REGISTRY: your_container_registry_url # e.g., 123456789012.dkr.ecr.ca-central-1.amazonaws.com
  EKS_CLUSTER_NAME: lucid-cluster-staging
  IMAGE_NAME: lucid-serving

jobs:
  deploy:
    name: Build and Deploy to Staging
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write # Required for AWS OIDC authentication
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::123456789012:role/github-actions-deploy-role # Replace with your IAM role ARN
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      id: build-image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} -f ml_platform/serving/Dockerfile.serving .
        docker push ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}
        echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
        kubectl config current-context

    - name: Deploy to KServe
      run: |
        # Replace placeholders in the kserve manifest
        IMAGE_TAG=${{ steps.build-image.outputs.image_tag }}
        REGISTRY_URL_ESC=$(echo "${{ env.ECR_REGISTRY }}" | sed 's/\//\\\//g') # Escape slashes for sed

        sed -i "s/your_container_registry_url/${REGISTRY_URL_ESC}/g" ml_platform/serving/kserve.yaml
        sed -i "s/IMAGE_TAG/${IMAGE_TAG}/g" ml_platform/serving/kserve.yaml
        
        echo "--- Applying KServe manifest ---"
        cat ml_platform/serving/kserve.yaml
        
        kubectl apply -f ml_platform/serving/kserve.yaml
        
        echo "--- Deployment initiated. Canary rollout started. ---"

    - name: Clean up
      run: |
        kubectl delete -f ml_platform/serving/kserve.yaml